### ISSUE TITLE
Copying returns error

### ISSUE THREAD

**Issue by Integral** [substance/archivist-writer#20]
Although you can copy, but console will output error `Uncaught TypeError: $ is not a function` which points to https://github.com/substance/substance/blob/master/src/document/node.js#L73

**Comment by michael** [comment]
@oliver---- can you take over this one.. I don't know how i should deal with that default Node.toHtml implementation, it's some leftback from the Tahi html stuff.

**Comment by michael** [comment]
You can reproduce and fix the error in archivist-writer `comments` branch.

**Comment by obuchtala** [comment]
Fixed.

FYI:
- there were bugs in the default exporter (Document.Node.toHtml)
- this method was used because ArchivistInterview.TextNode does not provide a toHtml implementation
- Beyond that it works now, as it uses the default exporter and the default importer now, but we should use Substance.Document.Paragraph instead of the custom text node in future.
